spring.application.name=AuthenticationServer
server.port = 7000
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=finsightDB

#spring.security.user.name=teja
#spring.security.user.password=pass

spring.mail.host=smtp.zoho.in
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
#Set these environment variable in your system using "SET MAIL_PASSWORD=your_password" and "SET MAIL_USERNAME=your_username" command
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.in
spring.mail.properties.mail.smtp.ssl.enable=true

#spring.mail.properties.mail.smtp.starttls.enable=true

