spring.application.name=AuthenticationServer
server.port = 7000
# spring.data.mongodb.host=127.0.0.1
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=finsightDB

#spring.security.user.name=teja
#spring.security.user.password=pass
spring.data.mongodb.uri=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.yf4psz7.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
#Set these environment variable in your system using "SET DB_USER=your_db_user", "SET DB_PASS=your_db_password", "SET DB_CLUSTER=your_db_cluster" and "SET DB_NAME=your_db_name" command
spring.mail.host=smtp.zoho.in
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
#Set these environment variable in your system using "SET MAIL_PASSWORD=your_password" and "SET MAIL_USERNAME=your_username" command
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.in
spring.mail.properties.mail.smtp.ssl.enable=true

#spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}